# Generated by Django 6.0 on 2025-12-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
